version: "3.8"
   
services:
  #Mysql
  db:
    image: mysql:5.7.13
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: cinemaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: passwd
    container_name: cinemaDB
  web:
    build: 
      context: .
      dockerfile: DockerFiles/python/pythonDF
    command: sh scripts/django.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000 
    depends_on:
      - db