# Generated by Django 3.1.2 on 2020-10-24 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='MoviesId',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='UserId',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='CinemaName',
        ),
        migrations.AddField(
            model_name='favorite',
            name='Movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='backend.movie'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='Cinema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Cinema', to='backend.cinema'),
        ),
    ]
